name: mobile_devices_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.4

dependencies:
  mobile_devices_api:
    path: ../mobile_devices_api

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
