name: daily_phones
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_pdfview: ^1.3.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^11.0.0
  get_it: ^7.7.0
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2
  path: ^1.9.0
  pdf: ^3.11.1
  printing: ^5.13.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.5.6
  syncfusion_flutter_pdfviewer: ^26.2.10
  uuid: ^4.4.0

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
